FROM ubuntu
WORKDIR /haresh/welcome
ADD welcome.txt welcome.txt
ENTRYPOINT cat welcome.txt
# This Dockerfile creates a simple image that prints "Hello, World!" when run.
# It uses the Ubuntu base image, sets the working directory to /haresh/welcome,
# adds a text file named welcome.txt to the image, and specifies the command to
# run when the container starts, which is to display the contents of welcome.txt.