version: "3.0"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./src/main/resources/init.js:/docker-entrypoint-initdb.d/init.js
  job-service:
    build: .
    image: job-service
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      spring.data.mongodb.uri: "mongodb://job_user:job_password@mongo:27017/jobs"