version: '3.0'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: product_db
    volumes:
      - ./data:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"

